from http.cookies import SimpleCookie
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal, Self

from ._wrapper import ffi
from .const import CurlECode, CurlHttpVersion, CurlInfo, CurlOpt, CurlWsFlag

DEFAULT_CACERT = ...
REASON_PHRASE_RE = ...
STATUS_LINE_RE = ...
if TYPE_CHECKING:
    class CurlWsFrame:
        age: int
        flags: int
        offset: int
        bytesleft: int
        len: int

class CurlError(Exception):
    def __init__(
        self,
        msg: str,
        code: int | CurlECode = ...,
        *args,
        **kwargs,
    ) -> None: ...

CURLINFO_TEXT = ...
CURLINFO_HEADER_IN = ...
CURLINFO_HEADER_OUT = ...
CURLINFO_DATA_IN = ...
CURLINFO_DATA_OUT = ...
CURLINFO_SSL_DATA_IN = ...
CURLINFO_SSL_DATA_OUT = ...
CURL_WRITEFUNC_PAUSE = ...
CURL_WRITEFUNC_ERROR = ...
CURL_READFUNC_ABORT = ...
CURL_READFUNC_PAUSE = ...
CURL_SEEKFUNC_OK = ...
CURL_SEEKFUNC_FAIL = ...
CURL_SEEKFUNC_CANTSEEK = ...
CURLPAUSE_RECV = ...
CURLPAUSE_RECV_CONT = ...
CURLPAUSE_SEND = ...
CURLPAUSE_SEND_CONT = ...
CURLPAUSE_ALL = ...
CURLPAUSE_CONT = ...

class _CallbackContext:
    def __init__(self, callback: Any) -> None: ...

@ffi.def_extern(onerror=_store_callback_error(0))
def debug_function(curl, type_: int, data, size: int, clientp) -> int: ...
def bytes_to_hex(b: bytes, uppercase: bool = ...) -> str: ...
def debug_function_default(type_: int, data: bytes) -> None: ...
@ffi.def_extern(onerror=_store_callback_error(CURL_WRITEFUNC_ERROR))
def buffer_callback(ptr, size, nmemb, userdata): ...
def ensure_int(s) -> int: ...
@ffi.def_extern(onerror=_store_callback_error(CURL_WRITEFUNC_ERROR))
def write_callback(ptr, size, nmemb, userdata) -> Literal[268435457, 4294967295]: ...
@ffi.def_extern(onerror=_store_callback_error(CURL_READFUNC_ABORT))
def read_buffer_callback(ptr, size, nmemb, userdata) -> int: ...
@ffi.def_extern(onerror=_store_callback_error(CURL_READFUNC_ABORT))
def read_callback(ptr, size, nmemb, userdata) -> int: ...
@ffi.def_extern(onerror=_store_callback_error(CURL_SEEKFUNC_FAIL))
def seek_buffer_callback(userdata, offset: int, origin: int) -> int: ...
def slist_to_list(head) -> list[bytes]: ...

class Curl:
    _WS_RECV_BUFFER_SIZE = ...
    def __init__(self, cacert: str = ..., debug: bool = ..., handle=...) -> None: ...
    def debug(self) -> None: ...
    def __del__(self) -> None: ...
    def setopt(self, option: CurlOpt, value: Any) -> int: ...
    def getinfo(self, option: CurlInfo) -> bytes | int | float | list[str | int]: ...
    def version(self) -> bytes: ...
    def impersonate(self, target: str, default_headers: bool = ...) -> int: ...
    def perform(self, clear_headers: bool = ..., clear_resolve: bool = ...) -> None: ...
    def upkeep(self) -> int: ...
    def pause(self, action: int) -> int: ...
    def clean_handles_and_buffers(
        self,
        clear_headers: bool = ...,
        clear_resolve: bool = ...,
    ) -> None: ...
    def duphandle(self) -> Curl: ...
    def reset(self) -> None: ...
    def parse_cookie_headers(self, headers: list[bytes]) -> SimpleCookie: ...
    @staticmethod
    def get_reason_phrase(status_line: bytes) -> bytes: ...
    @staticmethod
    def parse_status_line(status_line: bytes) -> tuple[CurlHttpVersion, int, bytes]: ...
    def close(self) -> None: ...
    def ws_recv(self) -> tuple[bytes, CurlWsFrame]: ...
    def ws_send(
        self,
        payload: bytes | memoryview,
        flags: CurlWsFlag | int = ...,
    ) -> int: ...
    def ws_close(self, code: int = ..., message: bytes = ...) -> int: ...

class CurlMime:
    def __init__(self, curl: Curl | None = ...) -> None: ...
    def addpart(
        self,
        name: str,
        *,
        content_type: str | None = ...,
        filename: str | None = ...,
        local_path: str | bytes | Path | None = ...,
        data: bytes | None = ...,
    ) -> None: ...
    @classmethod
    def from_list(cls, files: list[dict]) -> Self: ...
    def attach(self, curl: Curl | None = ...) -> None: ...
    def close(self) -> None: ...
    def __del__(self) -> None: ...
