def extract(
    filecontent: str | bytes,
    url: str | None = ...,
    *,
    output_format: str = ...,
    include_comments: bool = ...,
    include_tables: bool = ...,
    include_images: bool = ...,
    include_formatting: bool | None = ...,
    include_links: bool = ...,
    favor_precision: bool = ...,
    favor_recall: bool = ...,
    fast: bool = ...,
    deduplicate: bool = ...,
    with_metadata: bool = ...,
    only_with_metadata: bool = ...,
    target_language: str | None = ...,
    prune_xpath: str | list[str] | None = ...,
    **kwargs: object,
) -> str | None: ...
