# Stub for the 3.14 stdlib ``compression.zstd`` (PEP 784). The checkers pin
# 3.12, whose typeshed omits this module.

from collections.abc import Buffer

class ZstdError(Exception): ...

class ZstdCompressor:
    def __init__(self, level: int | None = None) -> None: ...
    def compress(self, data: Buffer, mode: int = ...) -> bytes: ...
    def flush(self, mode: int = ...) -> bytes: ...

def compress(data: Buffer, level: int | None = None) -> bytes: ...
def decompress(data: Buffer) -> bytes: ...
