MODE_GENERIC: int
MODE_TEXT: int
MODE_FONT: int

class Compressor:
    def __init__(
        self, mode: int = ..., quality: int = ..., lgwin: int = ..., lgblock: int = ...
    ) -> None: ...
    def process(self, string: bytes) -> bytes: ...
    def flush(self) -> bytes: ...
    def finish(self) -> bytes: ...

class Decompressor:
    def __init__(self) -> None: ...
    def process(self, string: bytes) -> bytes: ...
    def is_finished(self) -> bool: ...

def compress(
    string: bytes,
    mode: int = ...,
    quality: int = ...,
    lgwin: int = ...,
    lgblock: int = ...,
) -> bytes: ...
def decompress(string: bytes) -> bytes: ...

class error(Exception): ...
