from typing import Literal

import json

from ..const import CurlECode
from ..curl import CurlError

class RequestException(CurlError, OSError):
    def __init__(
        self,
        msg,
        code: CurlECode | Literal[0] = ...,
        response=...,
        *args,
        **kwargs,
    ) -> None: ...

class CookieConflict(RequestException): ...
class SessionClosed(RequestException): ...
class ImpersonateError(RequestException): ...
class InvalidJSONError(RequestException): ...
class JSONDecodeError(InvalidJSONError, json.JSONDecodeError): ...
class HTTPError(RequestException): ...
class IncompleteRead(HTTPError): ...
class ConnectionError(RequestException): ...
class DNSError(ConnectionError): ...
class ProxyError(RequestException): ...
class SSLError(ConnectionError): ...
class CertificateVerifyError(SSLError): ...
class Timeout(RequestException): ...
class ConnectTimeout(ConnectionError, Timeout): ...
class ReadTimeout(Timeout): ...
class URLRequired(RequestException): ...
class TooManyRedirects(RequestException): ...
class MissingSchema(RequestException, ValueError): ...
class InvalidSchema(RequestException, ValueError): ...
class InvalidURL(RequestException, ValueError): ...
class InvalidHeader(RequestException, ValueError): ...
class InvalidProxyURL(InvalidURL): ...
class ChunkedEncodingError(RequestException): ...
class ContentDecodingError(RequestException): ...
class StreamConsumedError(RequestException, TypeError): ...
class RetryError(RequestException): ...
class UnrewindableBodyError(RequestException): ...
class InterfaceError(RequestException): ...
class RequestsWarning(Warning): ...
class FileModeWarning(RequestsWarning, DeprecationWarning): ...
class RequestsDependencyWarning(RequestsWarning): ...

CODE2ERROR = ...

def code2error(
    code: CurlECode | Literal[0],
    msg: str,
) -> type[
    ProxyError
    | RequestException
    | InvalidSchema
    | InvalidURL
    | DNSError
    | ConnectionError
    | HTTPError
    | Timeout
    | SSLError
    | InterfaceError
    | TooManyRedirects
    | UnrewindableBodyError
    | CertificateVerifyError
    | IncompleteRead
]: ...
