from collections.abc import (
    ItemsView,
    Iterator,
    KeysView,
    Mapping,
    MutableMapping,
    Sequence,
    ValuesView,
)
from typing import overload

# House override: upstream ships ``get(self, key, default: Any = None) -> Any``
# while ``__getitem__`` is ``str | None``. ``get`` is ``self[key]`` or the
# default, so it is typed as such here.
type HeaderTypes = (
    Headers
    | Mapping[str, str | None]
    | Mapping[bytes, bytes | None]
    | Sequence[tuple[str, str]]
    | Sequence[tuple[bytes, bytes]]
    | Sequence[str | bytes]
)

SENSITIVE_HEADERS: set[str]

def to_str(value: str | bytes, encoding: str = "utf-8") -> str: ...
def obfuscate_sensitive_headers(
    items: Iterator[tuple[str | bytes, str | bytes]],
) -> Iterator[tuple[str | bytes, str | bytes]]: ...
def normalize_header_key(
    value: str | bytes, lower: bool, encoding: str | None = None
) -> bytes: ...
def normalize_header_value(
    value: str | bytes, encoding: str | None = None
) -> bytes: ...

class Headers(MutableMapping[str, str | None]):
    def __init__(
        self, headers: HeaderTypes | None = None, encoding: str | None = None
    ) -> None: ...
    @property
    def encoding(self) -> str: ...
    @encoding.setter
    def encoding(self, value: str) -> None: ...
    @property
    def raw(self) -> list[tuple[bytes, bytes | None]]: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[str | None]: ...
    def items(self) -> ItemsView[str, str | None]: ...
    def multi_items(self) -> list[tuple[str, str | None]]: ...
    @overload
    def get(self, key: str) -> str | None: ...
    @overload
    def get[T](self, key: str, default: T) -> str | T: ...
    def get_list(self, key: str, split_commas: bool = False) -> list[str | None]: ...
    def update(self, headers: HeaderTypes | None = None) -> None: ...
    def copy(self) -> Headers: ...
    def __getitem__(self, key: str) -> str | None: ...
    def __setitem__(self, key: str, value: str | None) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
